# Generated by Django 3.2.8 on 2021-11-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null='False', verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, null='False', verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='NA', max_length=50, null='False')),
                ('email_address', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('level', models.CharField(choices=[('100 Level', '100 Level'), ('200 Level', '200 Level'), ('Pre-degree/UABS', 'Pre-degree/UABS'), ('300 Level', '300 Level'), ('400 Level', '400 Level'), ('Final Year', 'Final Year'), ('Other', 'Other')], default='Other', max_length=50, null='False')),
                ('department', models.CharField(default='NA', max_length=100, null='False', verbose_name='Department')),
                ('unit', models.CharField(choices=[('No Unit', 'No Unit'), ('Bible Study Unit', 'Bible Study Unit'), ('Welfare Unit', 'Welfare Unit'), ('Evangelism Unit', 'Evangelism Unit'), ('Publicity Unit', 'Publicity Unit'), ('Organizing Unit', 'Organizing Unit'), ('Ushering Unit', 'Ushering Unit'), ('Choir Unit', 'Choir Unit'), ('Academic Unit', 'Academic Unit'), ('Drama Unit', 'Drama Unit'), ('Prayer Unit', 'Prayer Unit')], default='No Unit', max_length=50, null='False')),
                ('area', models.CharField(choices=[('Apatapiti', 'Apatapiti'), ('West Gate', 'West Gate'), ('Stateline', 'Stateline'), ('Akindeko', 'Akindeko'), ('Jibowu', 'Jibowu'), ('New Hostel male', 'New Hostel male'), ('New Hostel female', 'New Hostel female'), ('Road Block', 'Road Block'), ('Secretariat Area', 'Secretariat Area'), ('North Gate', 'North Gate'), ('Zion-Alejolowo', 'Zion-Alejolowo'), ('Jadesola', 'Jadesola'), ('Adeniyi', 'Adeniyi'), ('Abiola', 'Abiola'), ('WESCO area', 'WESCO area'), ('FUTASCOOPS', 'FUTASCOOPS'), ('Akad', 'Akad'), ('BSF Auditorium area', 'BSF Auditorium area'), ('Cassava/Oritaobele area', 'Cassava/Oritaobele area'), ('Embassy', 'Embassy'), ('Aba Area', 'Aba Area'), ('Redemption Area', 'Redemption Area'), ('Other', 'Other')], default='Other', max_length=50, null='False')),
                ('address', models.CharField(default='NA', max_length=50, null='False', verbose_name='Address')),
                ('phone_number', models.CharField(default='NA', max_length=25, null='False', verbose_name='Phone Number')),
                ('birthday', models.DateField(default='2000-01-01', null='False', verbose_name='Birthday')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='avatars/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
