# Generated by Django 3.2.7 on 2021-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
            ],
        ),
    ]
