# Generated by Django 3.2.8 on 2021-11-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsfapp', '0004_alter_profile_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit2',
            field=models.CharField(choices=[('No Unit', 'No Unit'), ('Bible Study Unit', 'Bible Study Unit'), ('Welfare Unit', 'Welfare Unit'), ('Evangelism Unit', 'Evangelism Unit'), ('Publicity Unit', 'Publicity Unit'), ('Organizing Unit', 'Organizing Unit'), ('Ushering Unit', 'Ushering Unit'), ('Choir Unit', 'Choir Unit'), ('Academic Unit', 'Academic Unit'), ('Drama Unit', 'Drama Unit'), ('Prayer Unit', 'Prayer Unit')], default='No Unit', max_length=50, null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(choices=[('Apatapiti', 'Apatapiti'), ('West Gate', 'West Gate'), ('Stateline', 'Stateline'), ('Akindeko', 'Akindeko'), ('Jibowu', 'Jibowu'), ('New Hostel male', 'New Hostel male'), ('New Hostel female', 'New Hostel female'), ('Road Block', 'Road Block'), ('Secretariat Area', 'Secretariat Area'), ('North Gate', 'North Gate'), ('Zion-Alejolowo', 'Zion-Alejolowo'), ('Jadesola', 'Jadesola'), ('Adeniyi', 'Adeniyi'), ('Abiola', 'Abiola'), ('WESCO area', 'WESCO area'), ('FUTASCOOPS', 'FUTASCOOPS'), ('Akad', 'Akad'), ('BSF Auditorium area', 'BSF Auditorium area'), ('Cassava/Oritaobele area', 'Cassava/Oritaobele area'), ('Embassy', 'Embassy'), ('Aba Area', 'Aba Area'), ('Redemption Area', 'Redemption Area'), ('Rotsam/Equity Area', 'Rotsam/Equity Area'), ('Other', 'Other')], default='Other', max_length=50, null='False'),
        ),
    ]
